"""Render ProofBundles as markdown for posting back. JSON form is the model itself."""

from __future__ import annotations

from .models import ProofBundle, RunMetrics, Slo, SloSignal, VerificationResult

_BADGE = {
    VerificationResult.PASS: "PASS — alert condition no longer satisfied",
    VerificationResult.REJECT: "REJECT — see verdict",
    VerificationResult.INCONCLUSIVE: "INCONCLUSIVE — verifier could not produce a clean comparison",
}


def render_markdown(bundle: ProofBundle) -> str:
    files_block = "\n".join(f"- `{f.path}`" for f in bundle.patch.files) or "_(no files)_"
    metrics_block = _render_metrics(bundle.alert.slo, bundle.baseline, bundle.patched)
    preview_block = _render_preview(bundle) if bundle.preview else ""

    explanation_block = (
        f"\n**Why the patch failed:** {bundle.explanation}\n"
        if bundle.explanation
        else ""
    )

    return f"""## mirrord verification: {_BADGE[bundle.result]}

**Alert:** {bundle.alert.title} (`{bundle.alert.id}`)
**Service:** `{bundle.alert.service}`
**Suggested by:** `{bundle.patch.model}` (confidence {bundle.patch.confidence:.2f})

### Suggested fix
{bundle.patch.summary}

**Files changed:**
{files_block}

**Hypothesis:** {bundle.patch.hypothesis}

**Expected signal change:** {bundle.patch.expected_signal_change}

### Stage 1 — automated verification

{metrics_block}

**Verdict:** {bundle.rationale}
{explanation_block}{preview_block}
---
_Generated by mirrord-sre-verifier at {bundle.generated_at.isoformat()}Z._
"""


def _render_metrics(slo: Slo | None, baseline: RunMetrics, patched: RunMetrics) -> str:
    """Render the SLO-aware metrics block when an SLO is attached; fall back
    to a generic baseline-vs-patched table otherwise."""
    if slo is None:
        return _render_metrics_legacy(baseline, patched)

    # Pretty signal labels for the table
    signal_label = {
        SloSignal.P50_MS: "p50 latency (ms)",
        SloSignal.P99_MS: "p99 latency (ms)",
        SloSignal.ERROR_RATE: "Error rate",
    }[slo.signal]

    fmt = (
        (lambda v: f"{v:.2%}") if slo.signal == SloSignal.ERROR_RATE
        else (lambda v: f"{v:.1f}")
    )
    threshold_fmt = fmt(slo.threshold)

    from .engine import _signal_value, _evaluate

    base_v = _signal_value(baseline, slo.signal)
    patched_v = _signal_value(patched, slo.signal)
    base_violates = _evaluate(base_v, slo.operator, slo.threshold)
    patched_violates = _evaluate(patched_v, slo.operator, slo.threshold)

    slo_table = f"""**SLO under verification:** `{signal_label.lower()} {slo.operator.value} {threshold_fmt}` (alert fires while this holds)

| | Baseline | Patched | SLO threshold | Status |
|---|---:|---:|---:|:---|
| {signal_label} | {fmt(base_v)} | {fmt(patched_v)} | {threshold_fmt} | {'❌ violates' if patched_violates else '✅ satisfies'} |
"""

    # Regression-watchlist table (other signals, sanity check)
    watch_rows = []
    for sig, label in [
        (SloSignal.P50_MS, "p50 latency (ms)"),
        (SloSignal.P99_MS, "p99 latency (ms)"),
        (SloSignal.ERROR_RATE, "Error rate"),
    ]:
        if sig == slo.signal:
            continue
        bv = _signal_value(baseline, sig)
        pv = _signal_value(patched, sig)
        f = (lambda v: f"{v:.2%}") if sig == SloSignal.ERROR_RATE else (lambda v: f"{v:.1f}")
        change = (
            f"{(pv - bv):+.2f}" if sig == SloSignal.ERROR_RATE
            else f"{_pct_change(bv, pv):+.1f}%"
        )
        watch_rows.append(f"| {label} | {f(bv)} | {f(pv)} | {change} |")
    watchlist = "\n".join(watch_rows)

    return f"""{slo_table}
**Regression watchlist** (other signals; not what the alert fired on):

| Signal | Baseline | Patched | Change |
|---|---:|---:|---:|
{watchlist}

Requests per run: {baseline.request_count}"""


def _render_metrics_legacy(baseline: RunMetrics, patched: RunMetrics) -> str:
    a, p = baseline, patched
    return f"""| Metric | Baseline | Patched | Change |
|---|---:|---:|---:|
| p50 latency (ms) | {a.duration_ms_p50:.1f} | {p.duration_ms_p50:.1f} | {_pct_change(a.duration_ms_p50, p.duration_ms_p50):+.1f}% |
| p99 latency (ms) | {a.duration_ms_p99:.1f} | {p.duration_ms_p99:.1f} | {_pct_change(a.duration_ms_p99, p.duration_ms_p99):+.1f}% |
| Error rate | {a.error_rate:.2%} | {p.error_rate:.2%} | {_pct_change(a.error_rate, p.error_rate):+.1f}% |
| Requests | {a.request_count} | {p.request_count} | — |"""


def _render_preview(bundle: ProofBundle) -> str:
    pv = bundle.preview
    assert pv is not None
    return f"""
### Stage 2 — live preview env

Stage 1 passed, so the patched candidate is up as an isolated preview pod via
the mirrord operator. Hit it from anywhere inside the cluster by adding the
session header to a normal request — prod traffic continues to hit the
unpatched pod, only your tagged requests get routed to the candidate.

- **env-key:** `{pv.env_key}`
- **image:** `{pv.image}`
- **target:** `{pv.target}` in `{pv.namespace}`
- **TTL:** {pv.ttl_minutes} minutes (auto-cleanup by operator)

**Try it:**
```bash
{pv.curl_recipe}
```

**Stop early:**
```bash
mirrord preview stop --key {pv.env_key} -t {pv.target} -n {pv.namespace}
```
"""


def _pct_change(before: float, after: float) -> float:
    if before == 0:
        return 0.0 if after == 0 else float("inf")
    return (after - before) / before * 100.0
